<xs:schema xmlns:ent="http://v8.1c.ru/8.1/data/enterprise" xmlns:tns="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:v8="http://v8.1c.ru/8.1/data/core" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://v8.1c.ru/8.1/data/enterprise/current-config" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:import namespace="http://v8.1c.ru/8.1/data/core"/>
	<xs:import namespace="http://v8.1c.ru/8.1/data/enterprise"/>
    <xs:simpleType name="CatalogRef.Номенклатура">
        <xs:restriction base="ent:AnyRef"/>
    </xs:simpleType>
    <xs:simpleType name="CatalogRef.КлассификаторЕдиницИзмерения">
        <xs:restriction base="ent:AnyRef"/>
    </xs:simpleType>
    <xs:simpleType name="CatalogRef.ЕдиницыИзмерения">
        <xs:restriction base="ent:AnyRef"/>
    </xs:simpleType>
	<xs:complexType name="CatalogObject.ЕдиницыИзмерения">
		<xs:sequence>
			<xs:element name="Ref" type="tns:CatalogRef.ЕдиницыИзмерения"/>
			<xs:element name="DeletionMark" type="xs:boolean"/>
			<xs:element name="Owner" type="ent:AnyRef"/>
			<xs:element name="Code" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="ЕдиницаПоКлассификатору" type="tns:CatalogRef.КлассификаторЕдиницИзмерения"/>
			<xs:element name="Вес" type="xs:decimal"/>
			<xs:element name="Объем" type="xs:decimal"/>
			<xs:element name="Коэффициент" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CatalogObject.КлассификаторЕдиницИзмерения">
		<xs:sequence>
			<xs:element name="Ref" type="tns:CatalogRef.КлассификаторЕдиницИзмерения"/>
			<xs:element name="DeletionMark" type="xs:boolean"/>
			<xs:element name="Code" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="НаименованиеПолное" type="xs:string"/>
			<xs:element name="МеждународноеСокращение" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="CatalogRef.НоменклатурныеГруппы">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:complexType name="CatalogObject.НоменклатурныеГруппы">
		<xs:sequence>
			<xs:element name="IsFolder" type="xs:boolean"/>
			<xs:element name="Ref" type="tns:CatalogRef.НоменклатурныеГруппы"/>
			<xs:element name="DeletionMark" type="xs:boolean"/>
			<xs:element name="Parent" type="tns:CatalogRef.НоменклатурныеГруппы"/>
			<xs:element name="Code" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="ЕдиницаХраненияОстатков" type="tns:CatalogRef.ЕдиницыИзмерения" minOccurs="0"/>
			<xs:element name="БазоваяЕдиницаИзмерения" type="tns:CatalogRef.КлассификаторЕдиницИзмерения" minOccurs="0"/>
			<xs:element name="СтавкаНДС" type="tns:EnumRef.СтавкиНДС" minOccurs="0"/>
			<xs:element name="НалоговоеНазначениеВПроизводстве" type="tns:CatalogRef.НалоговыеНазначенияАктивовИЗатрат" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="CatalogRef.ХранилищеДополнительнойИнформации">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.Контрагенты">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.Пользователи">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="EnumRef.СтавкиНДС">
		<xs:restriction base="xs:string">
			<xs:enumeration value=""/>
			<xs:enumeration value="НДС0"/>
			<xs:enumeration value="НДС14"/>
			<xs:enumeration value="БезНДС"/>
			<xs:enumeration value="НДС20"/>
			<xs:enumeration value="НДС7"/>
			<xs:enumeration value="НеНДС"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.СтатьиЗатрат">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.ВидыНоменклатуры">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.ЦеновыеГруппы">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.КлассификаторСтранМира">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.КлассификаторУКТВЭД">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.СтатьиНалоговыхДеклараций">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:complexType name="CatalogObject.Номенклатура">
		<xs:sequence>
			<xs:element name="IsFolder" type="xs:boolean"/>
			<xs:element name="Ref" type="tns:CatalogRef.Номенклатура"/>
			<xs:element name="DeletionMark" type="xs:boolean"/>
			<xs:element name="Parent" type="tns:CatalogRef.Номенклатура"/>
			<xs:element name="Code" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="Артикул" type="xs:string" minOccurs="0"/>
			<xs:element name="БазоваяЕдиницаИзмерения" type="tns:CatalogRef.КлассификаторЕдиницИзмерения" minOccurs="0"/>
			<xs:element name="Весовой" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ВесовойКоэффициентВхождения" type="xs:decimal" minOccurs="0"/>
			<xs:element name="ВестиПартионныйУчетПоСериям" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ВестиУчетПоСериям" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ВестиУчетПоХарактеристикам" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ЕдиницаДляОтчетов" type="tns:CatalogRef.ЕдиницыИзмерения" minOccurs="0"/>
			<xs:element name="ЕдиницаХраненияОстатков" type="tns:CatalogRef.ЕдиницыИзмерения" minOccurs="0"/>
			<xs:element name="Комментарий" type="xs:string" minOccurs="0"/>
			<xs:element name="ТранспортнаяУслуга" type="xs:boolean" minOccurs="0"/>
			<xs:element name="Набор" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ЛьготаНДС" type="xs:string" minOccurs="0"/>
			<xs:element name="НаименованиеПолное" type="xs:string" minOccurs="0"/>
			<xs:element name="НоменклатурнаяГруппа" type="tns:CatalogRef.НоменклатурныеГруппы" minOccurs="0"/>
			<xs:element name="НоменклатурнаяГруппаЗатрат" type="tns:CatalogRef.НоменклатурныеГруппы" minOccurs="0"/>
			<xs:element name="ОсновноеИзображение" type="tns:CatalogRef.ХранилищеДополнительнойИнформации" minOccurs="0"/>
			<xs:element name="ОсновнойПоставщик" type="tns:CatalogRef.Контрагенты" minOccurs="0"/>
			<xs:element name="ОтветственныйМенеджерЗаПокупки" type="tns:CatalogRef.Пользователи" minOccurs="0"/>
			<xs:element name="Услуга" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ИзмеряетсяТолькоВСуммовомВыражении" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ТекстДляПечатиВКолонкеКоличествоНалоговойНакладной" type="xs:string" minOccurs="0"/>
			<xs:element name="БланкСтрогогоУчета" type="xs:boolean" minOccurs="0"/>
			<xs:element name="УчитываетсяПоНоминальнойСтоимости" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ВидНоменклатуры" type="tns:CatalogRef.ВидыНоменклатуры"/>
			<xs:element name="ВестиСерийныеНомера" type="xs:boolean" minOccurs="0"/>
			<xs:element name="Комплект" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ЦеноваяГруппа" type="tns:CatalogRef.ЦеновыеГруппы" minOccurs="0"/>
			<xs:element name="ЕдиницаИзмеренияМест" type="tns:CatalogRef.ЕдиницыИзмерения" minOccurs="0"/>
			<xs:element name="ДополнительноеОписаниеНоменклатуры" type="xs:string" minOccurs="0"/>
			<xs:element name="СтранаПроисхождения" type="tns:CatalogRef.КлассификаторСтранМира" minOccurs="0"/>
			<xs:element name="НоменклатураГТД" nillable="true" minOccurs="0"/>
			<xs:element name="УДАЛИТЬКодУКТВЭД" type="tns:CatalogRef.КлассификаторУКТВЭД" minOccurs="0"/>
			<xs:element name="ПодакцизныйТовар" type="xs:boolean" minOccurs="0"/>
			<xs:element name="СтатьяДекларацииПоАкцизномуНалогу" type="tns:CatalogRef.СтатьиНалоговыхДеклараций" minOccurs="0"/>
			<xs:element name="КодЛьготы" type="xs:string" minOccurs="0"/>
			<xs:element name="УказыватьШтрихкодАкцизнойМаркиПриПечатиЧека" type="xs:boolean" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="CatalogRef.Склады">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.ХарактеристикиНоменклатуры">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.СерииНоменклатуры">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.Качество">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:complexType name="AccumulationRegisterRecord.ТоварыНаСкладах">
		<xs:sequence>
			<xs:element name="Recorder" nillable="true"/>
			<xs:element name="Period" type="xs:dateTime"/>
			<xs:element name="RecordType" type="ent:AccumulationRecordType"/>
			<xs:element name="Active" type="xs:boolean"/>
			<xs:element name="Склад" type="tns:CatalogRef.Склады"/>
			<xs:element name="Номенклатура" type="tns:CatalogRef.Номенклатура"/>
			<xs:element name="ХарактеристикаНоменклатуры" type="tns:CatalogRef.ХарактеристикиНоменклатуры"/>
			<xs:element name="СерияНоменклатуры" type="tns:CatalogRef.СерииНоменклатуры"/>
			<xs:element name="Качество" type="tns:CatalogRef.Качество"/>
			<xs:element name="Количество" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="EnumRef.ВидыСкладов">
		<xs:restriction base="xs:string">
			<xs:enumeration value=""/>
			<xs:enumeration value="Оптовый"/>
			<xs:enumeration value="Розничный"/>
			<xs:enumeration value="НТТ"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.ТипыЦенНоменклатуры">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.Валюты">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:complexType name="CatalogObject.Валюты">
		<xs:sequence>
			<xs:element name="Ref" type="tns:CatalogRef.Валюты"/>
			<xs:element name="DeletionMark" type="xs:boolean"/>
			<xs:element name="Code" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="НаименованиеПолное" type="xs:string"/>
			<xs:element name="ПараметрыПрописиНаРусском" type="xs:string"/>
			<xs:element name="ПараметрыПрописиНаУкраинском" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CatalogObject.ТипыЦенНоменклатуры">
		<xs:sequence>
			<xs:element name="Ref" type="tns:CatalogRef.ТипыЦенНоменклатуры"/>
			<xs:element name="DeletionMark" type="xs:boolean"/>
			<xs:element name="Code" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="ВалютаЦены" type="tns:CatalogRef.Валюты"/>
			<xs:element name="БазовыйТипЦен" type="tns:CatalogRef.ТипыЦенНоменклатуры"/>
			<xs:element name="Рассчитывается" type="xs:boolean"/>
			<xs:element name="ПроцентСкидкиНаценки" type="xs:decimal"/>
			<xs:element name="ЦенаВключаетНДС" type="xs:boolean"/>
			<xs:element name="ПорядокОкругления" type="tns:EnumRef.ПорядкиОкругления"/>
			<xs:element name="ОкруглятьВБольшуюСторону" type="xs:boolean"/>
			<xs:element name="Комментарий" type="xs:string"/>
			<xs:element name="СпособРасчетаЦены" type="tns:EnumRef.СпособыРасчетаЦены"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="EnumRef.ПорядкиОкругления">
		<xs:restriction base="xs:string">
			<xs:enumeration value=""/>
			<xs:enumeration value="Окр0_01"/>
			<xs:enumeration value="Окр0_05"/>
			<xs:enumeration value="Окр0_1"/>
			<xs:enumeration value="Окр0_5"/>
			<xs:enumeration value="Окр1"/>
			<xs:enumeration value="Окр5"/>
			<xs:enumeration value="Окр10"/>
			<xs:enumeration value="Окр50"/>
			<xs:enumeration value="Окр100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="EnumRef.СпособыРасчетаЦены">
		<xs:restriction base="xs:string">
			<xs:enumeration value=""/>
			<xs:enumeration value="ПоПроцентнойНаценкеНаБазовыйТип"/>
			<xs:enumeration value="ПоВхождениюБазовойЦеныВДиапазон"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.Подразделения">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:complexType name="CatalogObject.Подразделения">
		<xs:sequence>
			<xs:element name="Ref" type="tns:CatalogRef.Подразделения"/>
			<xs:element name="DeletionMark" type="xs:boolean"/>
			<xs:element name="Parent" type="tns:CatalogRef.Подразделения"/>
			<xs:element name="Code" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CatalogObject.Склады">
		<xs:sequence>
			<xs:element name="IsFolder" type="xs:boolean"/>
			<xs:element name="Ref" type="tns:CatalogRef.Склады"/>
			<xs:element name="DeletionMark" type="xs:boolean"/>
			<xs:element name="Parent" type="tns:CatalogRef.Склады"/>
			<xs:element name="Code" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="Комментарий" type="xs:string" minOccurs="0"/>
			<xs:element name="ТипЦенРозничнойТорговли" type="tns:CatalogRef.ТипыЦенНоменклатуры" minOccurs="0"/>
			<xs:element name="Подразделение" type="tns:CatalogRef.Подразделения" minOccurs="0"/>
			<xs:element name="ВидСклада" type="tns:EnumRef.ВидыСкладов" minOccurs="0"/>
			<xs:element name="НомерСекции" type="xs:decimal" minOccurs="0"/>
			<xs:element name="РасчетРозничныхЦенПоТорговойНаценке" type="xs:boolean" minOccurs="0"/>
			<xs:element name="СуммовойУчет" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ТерриторияПоКОАТУУ" type="tns:CatalogRef.КлассификаторКОАТУУ" minOccurs="0"/>
			<xs:element name="Местонахождение" type="xs:string" minOccurs="0"/>
			<xs:element name="КодКАТОТТГ" type="xs:string" minOccurs="0"/>
			<xs:element name="НалоговаяИнспекция" type="tns:CatalogRef.НалоговыеИнспекции" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="EnumRef.ЮрФизЛицо">
		<xs:restriction base="xs:string">
			<xs:enumeration value=""/>
			<xs:enumeration value="ЮрЛицо"/>
			<xs:enumeration value="ФизЛицо"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="CatalogObject.Регионы">
		<xs:sequence>
			<xs:element name="Ref" type="tns:CatalogRef.Регионы"/>
			<xs:element name="DeletionMark" type="xs:boolean"/>
			<xs:element name="Parent" type="tns:CatalogRef.Регионы"/>
			<xs:element name="Code" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="Комментарий" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="CatalogRef.КлассификаторКОАТУУ">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.НалоговыеИнспекции">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.Регионы">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.БанковскиеСчета">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.ДоговорыКонтрагентов">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.ИсточникиИнформацииПриОбращенииПокупателей">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.КонтактныеЛицаКонтрагентов">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.ВидыДеятельностиКонтрагентов">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.ГруппыДоступаККонтрагентам">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:simpleType name="CatalogRef.">
		<xs:restriction base="ent:AnyRef"/>
	</xs:simpleType>
	<xs:complexType name="CatalogObject.Контрагенты">
		<xs:sequence>
			<xs:element name="IsFolder" type="xs:boolean"/>
			<xs:element name="Ref" type="tns:CatalogRef.Контрагенты"/>
			<xs:element name="DeletionMark" type="xs:boolean"/>
			<xs:element name="Parent" type="tns:CatalogRef.Контрагенты"/>
			<xs:element name="Code" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="ОсновнойДоговорКонтрагента" type="tns:CatalogRef.ДоговорыКонтрагентов" minOccurs="0"/>
			<xs:element name="Комментарий" type="xs:string"/>
			<xs:element name="ГоловнойКонтрагент" type="tns:CatalogRef.Контрагенты" minOccurs="0"/>
			<xs:element name="ЮрФизЛицо" type="tns:EnumRef.ЮрФизЛицо" minOccurs="0"/>
			<xs:element name="Покупатель" type="xs:boolean" minOccurs="0"/>
			<xs:element name="Поставщик" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ИНН" type="xs:string" minOccurs="0"/>
			<xs:element name="НаименованиеПолное" type="xs:string" minOccurs="0"/>
			<xs:element name="ОсновнойБанковскийСчет" type="tns:CatalogRef.БанковскиеСчета" minOccurs="0"/>
			<xs:element name="ДокументУдостоверяющийЛичность" type="xs:string" minOccurs="0"/>
			<xs:element name="ОсновнойМенеджерПокупателя" type="tns:CatalogRef.Пользователи" minOccurs="0"/>
			<xs:element name="ДополнительноеОписание" type="xs:string" minOccurs="0"/>
			<xs:element name="РасписаниеРаботыСтрокой" type="xs:string" minOccurs="0"/>
			<xs:element name="СрокВыполненияЗаказаПоставщиком" type="xs:decimal" minOccurs="0"/>
			<xs:element name="ИсточникИнформацииПриОбращении" type="tns:CatalogRef.ИсточникиИнформацииПриОбращенииПокупателей" minOccurs="0"/>
			<xs:element name="ОсновноеКонтактноеЛицо" type="tns:CatalogRef.КонтактныеЛицаКонтрагентов" minOccurs="0"/>
			<xs:element name="ОсновнойВидДеятельности" type="tns:CatalogRef.ВидыДеятельностиКонтрагентов" minOccurs="0"/>
			<xs:element name="КодПоЕДРПОУ" type="xs:string" minOccurs="0"/>
			<xs:element name="НомерСвидетельства" type="xs:string" minOccurs="0"/>
			<xs:element name="ГруппаДоступаККонтрагенту" type="tns:CatalogRef.ГруппыДоступаККонтрагентам" minOccurs="0"/>
			<xs:element name="НеЯвляетсяРезидентом" type="xs:boolean" minOccurs="0"/>
			<xs:element name="Регион" type="tns:CatalogRef.Регионы" minOccurs="0"/>
			<xs:element name="ДополнятьНаименованиеАдресДаннымиГоловногоКонтрагентаВНН" type="xs:boolean" minOccurs="0"/>
			<xs:element name="КодФилиала" type="xs:string" minOccurs="0"/>
			<xs:element name="ИспользоватьЭДО1СЗвит" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ВидыДеятельности" type="tns:CatalogTabularSectionRow.Контрагенты.ВидыДеятельности" minOccurs="0" maxOccurs="99999"/>
			<xs:element name="МенеджерыПокупателя" type="tns:CatalogTabularSectionRow.Контрагенты.МенеджерыПокупателя" minOccurs="0" maxOccurs="99999"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CatalogTabularSectionRow.Контрагенты.ВидыДеятельности">
		<xs:sequence>
			<xs:element name="ВидДеятельности" type="tns:CatalogRef.ВидыДеятельностиКонтрагентов"/>
			<xs:element name="Ответственный" type="tns:CatalogRef.КонтактныеЛицаКонтрагентов"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CatalogTabularSectionRow.Контрагенты.МенеджерыПокупателя">
		<xs:sequence>
			<xs:element name="МенеджерПокупателя" type="tns:CatalogRef.Пользователи"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>